apiVersion: v2
name: pipeline
description: Tekton Helm Chart - Production-ready Kubernetes CI/CD pipelines for Tekton with webhook automation, least-privilege security, and multi-platform support

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.5.2

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

# Keywords for Helm Hub and search engines
keywords:
  - tekton
  - tekton-pipelines
  - ci-cd
  - kubernetes
  - continuous-integration
  - continuous-deployment
  - devops
  - pipelines
  - helm-chart
  - kaniko
  - buildah
  - github-webhooks
  - kubernetes-ci

# Home page and sources
home: https://github.com/cogitogroupltd/tekton-helm-chart
sources:
  - https://github.com/cogitogroupltd/tekton-helm-chart
  - https://tekton.dev

# Maintainers
maintainers:
  - name: Cogito Group Ltd
    url: https://cogitogroup.co.uk
