secret_ssh_key:
secret_ssh_cred: ssh-key
secret_docker_conf: docker-config
docker_config_json: 
secret_slack_webhook_uri: 

taskdefinitions:
  enabled: true
  serviceAccounts:
  - name: rolling-update
    yaml: |-
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: rolling-update
        namespace: tekton-pipelines
      ---
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: "cluster-administrator-ecr-build"
      subjects:
        - kind: ServiceAccount
          name: "rolling-update"
          namespace: tekton-pipelines
      roleRef:
        kind: ClusterRole
        name: cluster-admin
        apiGroup: rbac.authorization.k8s.io

pipelines:
  - name: prod 
    params:
    - name: git_revision
      description: The git revision
      default: "master"
    - name: git_revision_owner
      description: The owner of the git revision
      default: "git_owner_default_value"
    - name: git_branch_name
      description: The name of branch for the git revision
      default: "git_branch_name_default_value"
    - name: git_repository_name
      description: The name of the git repository
      default: "git_repository_name_default_value"
    workspaces:
      - name: git-pvc
      - name: image-cache
      - name: ssh-creds
      - name: docker-creds-cm
    trigger:
      eventTypes: [ "pull_request" ]
      eventActions: "['opened','synchronize','reopened']"
    taskcall:
    - name: git-clone
      taskRef:
        name: "git-clone"
      params:
      - name: url
        value: git@github.com:cogitogroupltd/docker-nginx-hello-world
      - name: revision #revision/commit
        value: $(params.git_revision)
      workspaces:
      - name: ssh-directory
        workspace: ssh-creds
      - name: output
        workspace: git-pvc
    - name: kaniko-build
      taskRef:
        name: kaniko-build
      params:
      - name: DOCKER_REGISTRY
        value: cogitoexample
      - name: DOCKER_REPOSITORY
        value: docker-nginx-hello-world
      - name: DOCKER_IMAGE_TAG
        value: $(params.git_revision)
      runAfter:
      - git-clone
      workspaces:
      - name: source
        workspace: git-pvc
      - name: dockerconfig
        workspace: docker-creds-cm
    - name: rolling-update
      taskRef:
        name: rolling-update
      params:
      - name: deployment
        value: nginx-app 
      - name: namespace
        value: default
      - name: tag
        value: $(params.git_revision)
      - name: git_repository_name
        value: $(params.git_repository_name)
      - name: docker_registry
        value: cogitoexample
      - name: docker_repository
        value: docker-nginx-hello-world
      runAfter:
      - kaniko-build